### ISSUE TITLE
Unable to install VulnAPI in Mac via Brew

### ISSUE THREAD

**Issue by jain6196** [cerberauth/vulnapi#164]
After running command `brew tap cerberauth/vulnapi` I tried installing vulnapi using `brew install vulnapi` 
I am getting an error as below
 
```
Warning: No available formula with the name "vulnapi".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for vulnapi.
```
![image](https://github.com/user-attachments/assets/96f19e31-9bc4-412f-8e4f-7e64ce1f6614)

**Comment by slaterx** [comment]
Based on [this](https://github.com/orgs/Homebrew/discussions/491),  the way that vulnapi setup their brew formula isn't the recommended way by homebrew. Due to that, this is the workaround I created to get the software installed:

``` 

brew tap cerberauth/vulnapi https://github.com/cerberauth/vulnapi
brew install $(brew --repository cerberauth/vulnapi)/vulnapi.rb

``` 

That made it possible install the software.

**Comment by emmanuelgautier** [comment]
It appears there was an error in the documentation. Sorry for that.
Thanks @slaterx for your help! Your solution has been added to the documentation.

The project should be published as a brew formula in a next version to ease the install for OSX. This should be available in the coming weeks.
