### ISSUE TITLE
unsupported security scheme type: apikey while running on a Swagger file

### ISSUE THREAD

**Issue by I-S-Tech** [cerberauth/vulnapi#216]
When running with my swagger file, I get an error

`unsupported security scheme type: apikey`

running command

`vulnapi scan openapi myswagger.yaml`

And having vulnapi installed from .deb package of the releases, and within a docker container.

While I can't post the entire Swagger, feel free to ask any question about it.

Thanks.

**Comment by emmanuelgautier** [comment]
Hi @I-S-Tech,

Thank you for reporting this issue! The API key security scheme is not yet supported, but I will work on it soon. Should be included in a next release in the coming weeks.

Could you please provide more details on how the API key is being passed? For example, is it passed as a bearer token in the header or in some other way?

**Comment by I-S-Tech** [comment]
Hi @emmanuelgautier, thanks for the reply !

Thanks for the precision, I look forward to the next release !

For the API key, here are the corresponding lines within the swagger file :

```yaml
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
```

**Comment by emmanuelgautier** [comment]
Hi @I-S-Tech,

The API Key security scheme is now supported in the new release v0.8.4. Please do not hesitate to test it.
